### ISSUE TITLE
Error in server_playerSetup.sqf (DayZ+ and Sahrani)

### ISSUE THREAD

**Issue by massl** [Stapo/Lite-Repo#1]
I have setup a dayz+ and sahrani server and get following error when a users connects:

DayZ+:
14:33:05   Error Type Any, expected Number
14:33:05 File z\addons\dayz_server\compile\server_playerSetup.sqf, line 159
14:33:05 Error in expression <os select 1) + _w),(_pos select 2)];
if(surfaceisWater _pos) exitWith {
_isIslan>
(endless loop)

Sahrani:
The same error happens on sahrani but it is line 197. The content (if clause) is the same. So I think it's the same bug.

Other Maps (e.g. Oring or Isladuala) work fine

**Comment by Stapo** [comment]
Would you be able to do some more extensive testing please, i cant seem to replicate it

**Comment by massl** [comment]
What exactly do you need to know? I have setup dayz+ and sahrani the same way like to other maps :/

Can we maybe talk in skype? I've sent you an email with my contact.

**Comment by Stapo** [comment]
just add me on skype directly: xx_stapo19_xx

i dont check emails :)

**Comment by massl** [comment]
Well. I failed ;)

For other people having this problem: don't rename your mission file, or at least call it $something.chernarus.pbo (for dayz+).
