### ISSUE TITLE
pSpawn endless loop

### ISSUE THREAD

**Issue by massl** [Stapo/Lite-Repo#3]
If the last spawnable vehicle has a chance of 0 the "CALL pSpawn" will run into an infinite loop.

As a solution the Chance should be at least 0.1 or the loop has to be cancelled after several runs.

Functions.sql: Fix in pMain before the CALL pSpawn() Loop:

UPDATE object_classes SET Chance=0.1 WHERE Chance < 0.1;

**Comment by DocTolly** [comment]
Probably better to skip the spawn loop if the chance is 0, atleast then you can prevent unwanted vehicles spawning :)

**Comment by massl** [comment]
Check the pSpawn() Function and you'll see that it is not that easy. You would have to SELECT every possible spawnable vehicle and check if there is at least one with a chance > 0. That's the only way to ensure that the function can spawn something.

**Comment by DocTolly** [comment]
I just submitted a pull request which fixes this issue in pMain :) The solution was very simple, thankfully!

**Comment by Stapo** [comment]
Done.
